steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'asia-south1-docker.pkg.dev/recruitmentinstitute-510113/recruitmentinstitute/recruitmentinstitute-web:latest'
      - '.'
images:
  - 'asia-south1-docker.pkg.dev/recruitmentinstitute-510113/recruitmentinstitute/recruitmentinstitute-web:latest'
timeout: '1200s'
options:
  machineType: 'E2_HIGHCPU_8'
