NODE_ENV: "production"
NEXT_TELEMETRY_DISABLED: "1"
SMTP_HOST: "smtp.gmail.com"
SMTP_PORT: "465"
SMTP_SECURE: "true"
SMTP_USER: "recruitmentinstitute5@gmail.com"
EMAIL_FROM: "recruitmentinstitute5@gmail.com"
EMAIL_FROM_NAME: "Recruitment Institute"
ADMIN_EMAIL: "sesasiba.es@gmail.com"
EMAIL_CC: "sesasiba.es@gmail.com,patilrupalib@gmail.com"
ADMIN_PHONE: "+917385204165"
ADMIN_WHATSAPP: "917385204165"
RAZORPAY_KEY_ID: "rzp_test_TUKkvyTnXzSVTP"
NEXT_PUBLIC_RAZORPAY_KEY_ID: "rzp_test_TUKkvyTnXzSVTP"
FASTAPI_SERVICE_URL: "https://recruitmentinstitute-api-396924250862.asia-south1.run.app"
NEXT_PUBLIC_API_URL: "https://recruitmentinstitute-api-396924250862.asia-south1.run.app"
AIDESK_SERVICE_URL: "https://recruitmentinstitute-aidesk-396924250862.asia-south1.run.app"
NEXT_PUBLIC_AIDESK_API_URL: "https://recruitmentinstitute-aidesk-396924250862.asia-south1.run.app"
GOOGLE_IMPERSONATE_EMAIL: "digitalaimlsystem@gmail.com"
