import type { Metadata } from 'next'
import { redirect, notFound } from 'next/navigation'
import Link from 'next/link'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { ChevronRight, BookOpen, FileDown } from 'lucide-react'
import { getUserSession } from '@/lib/auth'
import { getAssessmentNotes, FastApiError } from '@/lib/fastapiClient'

export const metadata: Metadata = {
  title: 'AI-Generated Notes',
  robots: { index: false, follow: false },
}

export default async function AssessmentNotesPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await getUserSession()
  if (!session || session.type !== 'student') redirect('/student-login')

  const { id } = await params
  const studentAssessmentId = Number(id)
  if (!studentAssessmentId) notFound()

  let notes
  try {
    notes = await getAssessmentNotes(studentAssessmentId)
  } catch (error) {
    if (error instanceof FastApiError && (error.status === 404 || error.status === 401)) notFound()
    throw error
  }

  return (
    <div style={{ maxWidth: 900, margin: '0 auto', padding: '28px 24px 70px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 16 }}>
        <Link href="/profile" style={{ fontSize: 12, fontWeight: 700, color: '#94a3b8', textDecoration: 'none' }}>Profile</Link>
        <ChevronRight style={{ width: 12, height: 12, color: '#cbd5e1' }} />
        <Link href={`/profile/assessments/${studentAssessmentId}`} style={{ fontSize: 12, fontWeight: 700, color: '#94a3b8', textDecoration: 'none' }}>Result</Link>
        <ChevronRight style={{ width: 12, height: 12, color: '#cbd5e1' }} />
        <span style={{ fontSize: 12, fontWeight: 700, color: '#1E40AF' }}>AI Notes</span>
      </div>

      <div style={{ marginBottom: 28, display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' }}>
        <div>
          <h1 style={{ fontSize: 32, fontWeight: 900, letterSpacing: '-0.03em', color: '#0f172a', lineHeight: 1.1 }}>AI-Generated Notes</h1>
          <p style={{ fontSize: 14, color: '#64748b', marginTop: 8 }}>Personalized notes for the topics you scored lowest on, generated by AI.</p>
        </div>
        <Link
          href={`/profile/assessments/${studentAssessmentId}`}
          style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '10px 16px', borderRadius: 12, background: '#F5F3FF', border: '1px solid #DDD6FE', color: '#7C3AED', fontSize: 13, fontWeight: 700, textDecoration: 'none', whiteSpace: 'nowrap' }}
        >
          <FileDown style={{ width: 14, height: 14 }} /> Back to Result
        </Link>
      </div>

      {notes.length === 0 ? (
        <div style={{ background: '#fff', border: '1px solid #e8ecf0', borderRadius: 20, padding: 40, textAlign: 'center' }}>
          <BookOpen style={{ width: 32, height: 32, color: '#94a3b8', margin: '0 auto 12px' }} />
          <p style={{ fontSize: 14, color: '#64748b' }}>No weak topics were identified — no extra notes were generated for this attempt.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
          {notes.map((note) => (
            <article key={note.id} style={{ background: '#fff', border: '1px solid #e8ecf0', borderRadius: 20, overflow: 'hidden', boxShadow: '0 1px 4px rgba(0,0,0,0.04)' }}>
              <div style={{ padding: '18px 24px', background: 'linear-gradient(135deg,#0f172a,#1e40af)', display: 'flex', alignItems: 'center', gap: 10 }}>
                <BookOpen style={{ width: 16, height: 16, color: '#fff' }} />
                <h2 style={{ fontSize: 16, fontWeight: 800, color: '#fff' }}>{note.topic_name}</h2>
              </div>
              <div style={{ padding: 24, fontSize: 14, color: '#334155', lineHeight: 1.8 }}>
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{note.notes_content}</ReactMarkdown>
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  )
}
